spring:
  datasource:
    username: root
    password: toor
    url: jdbc:mysql://192.168.199.199:3306/test
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource